### ISSUE TITLE
使用時一直跳出問題

### ISSUE THREAD

**Issue by stevensane** [Suwings/MCSManager#181]
一直開啟另一個視窗寫著錯誤代碼如下
{ Error: listen EADDRINUSE :::23333
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1045:20)
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at Server.listen (net.js:1478:7)
    at Function.serverListen [as listen] (M:\MCSM8.6.1\node_modules\express-ws\lib\index.js:42:40)
    at initializationProm (M:\MCSM8.6.1\app.js:259:9)
    at Object.<anonymous> (M:\MCSM8.6.1\app.js:284:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
使用計劃任務開啟伺服器好像會無限重啟

**Comment by Suwings** [comment]
Error: listen EADDRINUSE :::23333 意思是端口被占用，妳是不是開啟了兩個，又或者說這個端口運行了其他程序？檢查妳的23333端口是否運行著其他程序，或者說不小心運行了兩個面板。
