### ISSUE TITLE
更新到最新版本之后 出现大量报错

### ISSUE THREAD

**Issue by 982754469** [Suwings/MCSManager#211]
把原先所有文件删除 然后下载最新版 重新安装之后 这个面板出现了大量的报错
[ 2020-3-18 16:18:20 ] [ ERROR ] WebSocket 请求处理时异常:
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at MinecraftServer.send (/run/media/root/4cc7ff09-17d0-438c-b465-042fc32cb811/mc/core/Process/BaseMcserver.js:337:36)
    at ServerManager.sendMinecraftServer (/run/media/root/4cc7ff09-17d0-438c-b465-042fc32cb811/mc/core/Process/ServerCenter.js:117:42)
    at Object.module.exports.sendCommand (/run/media/root/4cc7ff09-17d0-438c-b465-042fc32cb811/mc/model/ServerModel.js:72:34)
    at Object.WebSocketObserver.listener [as CALLBACK] (/run/media/root/4cc7ff09-17d0-438c-b465-042fc32cb811/mc/route/websocket/console/command.js:39:25)
    at Object.module.exports.emit (/run/media/root/4cc7ff09-17d0-438c-b465-042fc32cb811/mc/model/ObserverModel.js:37:59)
    at Object.observerModel.listener [as CALLBACK] (/run/media/root/4cc7ff09-17d0-438c-b465-042fc32cb811/mc/model/WebSocketModel.js:7:19)
    at Object.module.exports.emit (/run/media/root/4cc7ff09-17d0-438c-b465-042fc32cb811/mc/model/ObserverModel.js:37:59)
--------Error-------
---------------------------------------------------------------------------------------------------------
这个报错不停循环重复刷 直到面板崩溃 希望得到解决方法

**Comment by huangsijun17** [comment]
更新过node吗？新版本的依赖要求提高了。

**Comment by 982754469** [comment]
用的是10.19.0版本的node 不清楚是否还要更新版本


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"huangsijun17"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月18日(星期三) 下午5:31
收件人:&nbsp;"Suwings/MCSManager"<MCSManager@noreply.github.com&gt;;
抄送:&nbsp;"梦幻云"<982754469@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Suwings/MCSManager] 更新到最新版本之后 出现大量报错 (#211)





 
更新过node吗？新版本的依赖要求提高了。

**Comment by huangsijun17** [comment]
什么操作系统？
有重新安装过吗？（`npm install`）
