### ISSUE TITLE
配置完成无法开服

### ISSUE THREAD

**Issue by Karlin-Z** [Suwings/MCSManager#229]
点击开服按钮无反应，服务端日志如下
[ 2020-4-11 7:58:29 ] [ INFO ] 用户  #master  正在启动  test1  服务端实例...                               
[ 2020-4-11 7:58:29 ] [ Minecraft Server start ] test1                                                     
[ 2020-4-11 7:58:29 ] [ INFO ] 服务器 [ test1 ] 启动进程:                                                  
[ 2020-4-11 7:58:29 ] [ INFO ] -------------------------------                                             
[ 2020-4-11 7:58:29 ] [ INFO ] 自定义参数启动:  bash start.sh                                              
[ 2020-4-11 7:58:29 ] [ INFO ] 根: ./server/server_core/test1                                              
[ 2020-4-11 7:58:29 ] [ INFO ] -------------------------------                                             
[ 2020-4-11 7:58:29 ] [ INFO ] [test1] >>> 进程创建                                                        
[ 2020-4-11 7:58:29 ] [ INFO ] [test1] >>> 进程退出

**Comment by Suwings** [comment]
不要使用  bash start.sh 这种写法，直接写 ./start.sh 或 sh ./start.sh，或者启动bash之后在命令输入框中输入 sh start.sh 命令，另外确认此文件编写正确，权限正确即可。

**Comment by Karlin-Z** [comment]
> 不要使用 bash start.sh 这种写法，直接写 ./start.sh 或 sh ./start.sh，或者启动bash之后在命令输入框中输入 sh start.sh 命令，另外确认此文件编写正确，权限正确即可。

尝试sh ./start.sh,仍然创建即退出，尝试./start.sh，报错，日志如下
2020-04-14 11:18:14:[ 2020-4-14 3:18:14 ] [ ERROR ] 服务端进程启动失败，建议检查启动命令与参数是否正确，pid:
2020-04-14 11:18:14:undefined
2020-04-14 11:18:14:--------Error-------
2020-04-14 11:18:14:
2020-04-14 11:18:14:[ 2020-4-14 3:18:14 ] [ ERROR ] 
2020-04-14 11:18:14:--------Error-------
2020-04-14 11:18:14:
2020-04-14 11:18:14:[ 2020-4-14 3:18:14 ] [ ERROR ] 服务器运行时异常,建议检查配置与环境
2020-04-14 11:18:14:Error: spawn ./start.sh EACCES
2020-04-14 11:18:14:    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
2020-04-14 11:18:14:    at onErrorNT (internal/child_process.js:469:16)
2020-04-14 11:18:14:    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
2020-04-14 11:18:14:  errno: 'EACCES',
2020-04-14 11:18:14:  code: 'EACCES',
2020-04-14 11:18:14:  syscall: 'spawn ./start.sh',
2020-04-14 11:18:14:  path: './start.sh',
2020-04-14 11:18:14:  spawnargs: []
2020-04-14 11:18:14:}
2020-04-14 11:18:14:--------Error-------
2020-04-14 11:18:14:
2020-04-14 11:18:14:[ 2020-4-14 3:18:14 ] [ ERROR ] 
2020-04-14 11:18:14:--------Error-------
2020-04-14 11:18:14:
2020-04-14 11:18:14:[ 2020-4-14 3:18:14 ] [ ERROR ] 错误报告:
2020-04-14 11:18:14:TypeError: Cannot read property 'pid' of undefined
2020-04-14 11:18:14:    at ChildProcess. (/MCSManager/core/Process/BaseMcserver.js:302:113)
2020-04-14 11:18:14:    at ChildProcess.emit (events.js:310:20)
2020-04-14 11:18:14:    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
2020-04-14 11:18:14:    at onErrorNT (internal/child_process.js:469:16)
2020-04-14 11:18:14:    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-04-14 11:18:14:--------Error-------

**Comment by Karlin-Z** [comment]
start文件内容如下
LD_LIBRARY_PATH=. ./bedrock_server
权限正确

**Comment by huangsijun17** [comment]
基岩版？
直接把开服命令改成
“LD_LIBRARY_PATH=.&&./bedrock_server”试试看

**Comment by Karlin-Z** [comment]
> 基岩版？
> 直接把开服命令改成
> “LD_LIBRARY_PATH=.&&./bedrock_server”试试看

是基岩版，已尝试无效

**Comment by Kiritow** [comment]
复现了问题，自定义命令或框架启动秒退，看journalctl -f看不出问题，最后发现进程启动的时候环境变量PATH未包含java，启动失败
