### ISSUE TITLE
Docker部署MCSM，运行mod服出现No such file or directory

### ISSUE THREAD

**Issue by zhjcreator** [Suwings/MCSManager#317]
怀疑是node.js 的docker缺乏中文支持，但从mcbbs嫖的mod服的mod的名字含有中文的原因。
尝试使用dpkg-reconfigure locales换中文环境没有效果，执行locale指令，LANG处为空。
因为不太了解debian，想问问大佬们有什么解决方案，或者是其它什么原因导致的
下面是部分报错
`java.io.FileNotFoundException: mods/??????????????????RedstoneFlux.jar (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:130)
        at red.mohist.forge.FindClassInMod.checkFile(FindClassInMod.java:72)
        at red.mohist.forge.FindClassInMod.checkDirectory(FindClassInMod.java:59)
        at red.mohist.forge.FindClassInMod.jar(FindClassInMod.java:102)
        at red.mohist.Mohist.main(Mohist.java:37)
java.io.FileNotFoundException: mods/??????????????????Draconic-Evolution.jar (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:130)
        at red.mohist.forge.FindClassInMod.checkFile(FindClassInMod.java:72)
        at red.mohist.forge.FindClassInMod.checkDirectory(FindClassInMod.java:59)
        at red.mohist.forge.FindClassInMod.jar(FindClassInMod.java:102)
        at red.mohist.Mohist.main(Mohist.java:37)`

**Comment by Suwings** [comment]
这个似乎是 Minecraft 服务端的报错，可以看见中文路径部分已经乱码，所以我认为确实极有可能是中文路径导致的问题，可以考虑把所有文件命名成英文来尝试解决。

至于其他方法，我也无能为力。

**Comment by zhjcreator** [comment]
> 这个似乎是 Minecraft 服务端的报错，可以看见中文路径部分已经乱码，所以我认为确实极有可能是中文路径导致的问题，可以考虑把所有文件命名成英文来尝试解决。
> 
> 至于其他方法，我也无能为力。

我之后试试看docker部署mcsm然后用它里面的docker部署服务端
还有一个小问题请教一下您，我是用群晖部署MCSManager的，但是不管是直接宿主机部署还是docker部署，内存显示都有问题。
![image](https://user-images.githubusercontent.com/55911606/93667785-03ee5200-fabb-11ea-857b-c2d9cc420ca5.png)
![image](https://user-images.githubusercontent.com/55911606/93667798-22ece400-fabb-11ea-97ec-c241b523b465.png)

**Comment by Suwings** [comment]
是面板的内存获取方式稍微有点问题，你的内存显示是正确的。
目前 nodejs 的 API 获取内存返回的就是这样的值，面板也只是直接显示这个值。

后期会想代替方法来解决这个小问题。
