### ISSUE TITLE
点击开启服务器失败

### ISSUE THREAD

**Issue by leafwalktuffy** [Suwings/MCSManager#335]
> 2020-11-12T16:33:32.082 INFO [demotest] >>> 准许用户 #master 控制台监听 
2020-11-12T16:33:34.174 INFO 用户  #master  正在启动  demotest  服务端实例... 
2020-11-12T16:33:34.174 INFO Minecraft Server start - demotest
2020-11-12T16:33:34.174 INFO 服务器 [ demotest ] 启动进程: 
2020-11-12T16:33:34.175 INFO ------------------------------- 
2020-11-12T16:33:34.175 INFO 启动:  java -Djline.terminal=jline.UnsupportedTerminal -jar Spigot-1.12.2-f982156_22564a9-20171203-0421.jar nogui 
2020-11-12T16:33:34.175 INFO 根: ./server/server_core/demotest 
2020-11-12T16:33:34.175 INFO ------------------------------- 
2020-11-12T16:33:34.179 ERROR 服务端进程启动失败，建议检查启动命令与参数是否正确，pid:
2020-11-12T16:33:34.180 ERROR 服务器运行时异常,建议检查配置与环境
2020-11-12T16:33:34.180 ERROR Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs: [
    '-Djline.terminal=jline.UnsupportedTerminal',
    '-jar',
    'Spigot-1.12.2-f982156_22564a9-20171203-0421.jar',
    'nogui'
  ]
}
2020-11-12T16:33:34.181 ERROR 错误报告:
2020-11-12T16:33:34.181 ERROR TypeError: Cannot read property 'pid' of undefined
    at ChildProcess.<anonymous> (/opt/MCSManager/core/Process/BaseMcserver.js:298:107)
    at ChildProcess.emit (events.js:311:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-11-12T16:33:34.528 ERROR WebSocket 请求处理时异常:
2020-11-12T16:33:34.528 ERROR TypeError: Cannot read property 'dataModel' of undefined
    at Object.CALLBACK (/opt/MCSManager/route/websocket/console/console-info.js:20:30)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at Object.CALLBACK (/opt/MCSManager/model/WebSocketModel.js:6:17)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at WebSocket.<anonymous> (/opt/MCSManager/route/websocket.js:170:27)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/opt/MCSManager/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/opt/MCSManager/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/opt/MCSManager/node_modules/ws/lib/receiver.js:346:17)
2020-11-12T16:33:37.525 ERROR WebSocket 请求处理时异常:
2020-11-12T16:33:37.525 ERROR TypeError: Cannot read property 'dataModel' of undefined
    at Object.CALLBACK (/opt/MCSManager/route/websocket/console/console-info.js:20:30)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at Object.CALLBACK (/opt/MCSManager/model/WebSocketModel.js:6:17)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at WebSocket.<anonymous> (/opt/MCSManager/route/websocket.js:170:27)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/opt/MCSManager/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/opt/MCSManager/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/opt/MCSManager/node_modules/ws/lib/receiver.js:346:17)
2020-11-12T16:33:40.524 ERROR WebSocket 请求处理时异常:
2020-11-12T16:33:40.526 ERROR TypeError: Cannot read property 'dataModel' of undefined
    at Object.CALLBACK (/opt/MCSManager/route/websocket/console/console-info.js:20:30)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at Object.CALLBACK (/opt/MCSManager/model/WebSocketModel.js:6:17)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at WebSocket.<anonymous> (/opt/MCSManager/route/websocket.js:170:27)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/opt/MCSManager/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/opt/MCSManager/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/opt/MCSManager/node_modules/ws/lib/receiver.js:346:17)
2020-11-12T16:33:43.524 ERROR WebSocket 请求处理时异常:
2020-11-12T16:33:43.524 ERROR TypeError: Cannot read property 'dataModel' of undefined
    at Object.CALLBACK (/opt/MCSManager/route/websocket/console/console-info.js:20:30)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at Object.CALLBACK (/opt/MCSManager/model/WebSocketModel.js:6:17)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at WebSocket.<anonymous> (/opt/MCSManager/route/websocket.js:170:27)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/opt/MCSManager/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/opt/MCSManager/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/opt/MCSManager/node_modules/ws/lib/receiver.js:346:17)
2020-11-12T16:33:46.524 ERROR WebSocket 请求处理时异常:
2020-11-12T16:33:46.525 ERROR TypeError: Cannot read property 'dataModel' of undefined
    at Object.CALLBACK (/opt/MCSManager/route/websocket/console/console-info.js:20:30)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at Object.CALLBACK (/opt/MCSManager/model/WebSocketModel.js:6:17)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at WebSocket.<anonymous> (/opt/MCSManager/route/websocket.js:170:27)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/opt/MCSManager/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/opt/MCSManager/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/opt/MCSManager/node_modules/ws/lib/receiver.js:346:17)
2020-11-12T16:33:49.530 ERROR WebSocket 请求处理时异常:
2020-11-12T16:33:49.530 ERROR TypeError: Cannot read property 'dataModel' of undefined
    at Object.CALLBACK (/opt/MCSManager/route/websocket/console/console-info.js:20:30)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at Object.CALLBACK (/opt/MCSManager/model/WebSocketModel.js:6:17)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at WebSocket.<anonymous> (/opt/MCSManager/route/websocket.js:170:27)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/opt/MCSManager/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/opt/MCSManager/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/opt/MCSManager/node_modules/ws/lib/receiver.js:346:17)
2020-11-12T16:33:52.525 ERROR WebSocket 请求处理时异常:
2020-11-12T16:33:52.525 ERROR TypeError: Cannot read property 'dataModel' of undefined
    at Object.CALLBACK (/opt/MCSManager/route/websocket/console/console-info.js:20:30)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at Object.CALLBACK (/opt/MCSManager/model/WebSocketModel.js:6:17)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at WebSocket.<anonymous> (/opt/MCSManager/route/websocket.js:170:27)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/opt/MCSManager/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/opt/MCSManager/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/opt/MCSManager/node_modules/ws/lib/receiver.js:346:17)
2020-11-12T16:33:55.523 ERROR WebSocket 请求处理时异常:
2020-11-12T16:33:55.523 ERROR TypeError: Cannot read property 'dataModel' of undefined
    at Object.CALLBACK (/opt/MCSManager/route/websocket/console/console-info.js:20:30)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at Object.CALLBACK (/opt/MCSManager/model/WebSocketModel.js:6:17)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at WebSocket.<anonymous> (/opt/MCSManager/route/websocket.js:170:27)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/opt/MCSManager/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/opt/MCSManager/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/opt/MCSManager/node_modules/ws/lib/receiver.js:346:17)
2020-11-12T16:33:58.523 ERROR WebSocket 请求处理时异常:
2020-11-12T16:33:58.523 ERROR TypeError: Cannot read property 'dataModel' of undefined
    at Object.CALLBACK (/opt/MCSManager/route/websocket/console/console-info.js:20:30)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at Object.CALLBACK (/opt/MCSManager/model/WebSocketModel.js:6:17)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at WebSocket.<anonymous> (/opt/MCSManager/route/websocket.js:170:27)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/opt/MCSManager/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/opt/MCSManager/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/opt/MCSManager/node_modules/ws/lib/receiver.js:346:17)
2020-11-12T16:34:01.525 ERROR WebSocket 请求处理时异常:
2020-11-12T16:34:01.525 ERROR TypeError: Cannot read property 'dataModel' of undefined
    at Object.CALLBACK (/opt/MCSManager/route/websocket/console/console-info.js:20:30)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at Object.CALLBACK (/opt/MCSManager/model/WebSocketModel.js:6:17)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at WebSocket.<anonymous> (/opt/MCSManager/route/websocket.js:170:27)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/opt/MCSManager/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/opt/MCSManager/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/opt/MCSManager/node_modules/ws/lib/receiver.js:346:17)
2020-11-12T16:34:04.531 ERROR WebSocket 请求处理时异常:
2020-11-12T16:34:04.531 ERROR TypeError: Cannot read property 'dataModel' of undefined
    at Object.CALLBACK (/opt/MCSManager/route/websocket/console/console-info.js:20:30)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at Object.CALLBACK (/opt/MCSManager/model/WebSocketModel.js:6:17)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at WebSocket.<anonymous> (/opt/MCSManager/route/websocket.js:170:27)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/opt/MCSManager/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/opt/MCSManager/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/opt/MCSManager/node_modules/ws/lib/receiver.js:346:17)
2020-11-12T16:34:07.524 ERROR WebSocket 请求处理时异常:
2020-11-12T16:34:07.524 ERROR TypeError: Cannot read property 'dataModel' of undefined
    at Object.CALLBACK (/opt/MCSManager/route/websocket/console/console-info.js:20:30)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at Object.CALLBACK (/opt/MCSManager/model/WebSocketModel.js:6:17)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at WebSocket.<anonymous> (/opt/MCSManager/route/websocket.js:170:27)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/opt/MCSManager/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/opt/MCSManager/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/opt/MCSManager/node_modules/ws/lib/receiver.js:346:17)
2020-11-12T16:34:10.523 ERROR WebSocket 请求处理时异常:
2020-11-12T16:34:10.523 ERROR TypeError: Cannot read property 'dataModel' of undefined
    at Object.CALLBACK (/opt/MCSManager/route/websocket/console/console-info.js:20:30)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at Object.CALLBACK (/opt/MCSManager/model/WebSocketModel.js:6:17)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at WebSocket.<anonymous> (/opt/MCSManager/route/websocket.js:170:27)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/opt/MCSManager/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/opt/MCSManager/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/opt/MCSManager/node_modules/ws/lib/receiver.js:346:17)
2020-11-12T16:34:13.524 ERROR WebSocket 请求处理时异常:
2020-11-12T16:34:13.524 ERROR TypeError: Cannot read property 'dataModel' of undefined
    at Object.CALLBACK (/opt/MCSManager/route/websocket/console/console-info.js:20:30)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at Object.CALLBACK (/opt/MCSManager/model/WebSocketModel.js:6:17)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at WebSocket.<anonymous> (/opt/MCSManager/route/websocket.js:170:27)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/opt/MCSManager/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/opt/MCSManager/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/opt/MCSManager/node_modules/ws/lib/receiver.js:346:17)
2020-11-12T16:34:16.524 ERROR WebSocket 请求处理时异常:
2020-11-12T16:34:16.524 ERROR TypeError: Cannot read property 'dataModel' of undefined
    at Object.CALLBACK (/opt/MCSManager/route/websocket/console/console-info.js:20:30)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at Object.CALLBACK (/opt/MCSManager/model/WebSocketModel.js:6:17)
    at Object.module.exports.emit (/opt/MCSManager/model/ObserverModel.js:36:53)
    at WebSocket.<anonymous> (/opt/MCSManager/route/websocket.js:170:27)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/opt/MCSManager/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/opt/MCSManager/node_modules/ws

**Comment by leafwalktuffy** [comment]
这是java环境配置错误吗  我需要在哪里修改我的java环境配置？

**Comment by TianBM** [comment]
我也遇到了类似情况，现在正在排查
日志部分：
`2020-11-15T15:23:31.499 INFO [new_server_2594000] >>> 准许用户 #BigMonster 控制台监听
2020-11-15T15:23:32.550 INFO 用户  #BigMonster  正在启动  new_server_2594000  服务端实例...
2020-11-15T15:23:32.550 INFO Minecraft Server start - new_server_2594000
2020-11-15T15:23:32.550 INFO 服务器 [ new_server_2594000 ] 启动进程:
2020-11-15T15:23:32.550 INFO -------------------------------
2020-11-15T15:23:32.550 INFO 自定义参数启动:  java -Xms1300m -Xmx1300m -jar mcx.jar
2020-11-15T15:23:32.550 INFO 根: ./server/server_core/new_server_2594000/
2020-11-15T15:23:32.550 INFO -------------------------------
2020-11-15T15:23:32.554 ERROR 服务端进程启动失败，建议检查启动命令与参数是否正确，pid:
2020-11-15T15:23:32.554 ERROR 服务器运行时异常,建议检查配置与环境
2020-11-15T15:23:32.554 ERROR Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs: [ '-Xms1300m', '-Xmx1300m', '-jar', 'mcx.jar' ]
}
2020-11-15T15:23:32.555 ERROR 错误报告:
2020-11-15T15:23:32.555 ERROR TypeError: Cannot read property 'pid' of undefined
    at ChildProcess.<anonymous> (/opt/MCSManager/core/Process/BaseMcserver.js:298:107)
    at ChildProcess.emit (events.js:311:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

定位的代码是创建子线程失败，报找不到文件

但是Java环境正常：
`➜  ~ java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
`

**Comment by Suwings** [comment]
看见较晚，深夜回复一下，不知道你们是否已经解决了这个问题？

一般这种错误都是通过命令启动进程失败所导致的。介于@leafwalktuffy的错误信息，极为有可能是Java环境未能正确安装。

关于@TianBM 的错误信息，Java环境安装正常，会不会是某些参数填写有点问题，可以试试去掉最大内存最小内存等等。

**Comment by TianBM** [comment]
嗯，已经解决了，重新按照Java安装步骤，在添加软连接后正常了
