### ISSUE TITLE
不知道为啥不能启动

### ISSUE THREAD

**Issue by yzy613** [Suwings/MCSManager#344]
**系统环境:**
Ubuntu Server 20.04 LTS x86_64
**面板版本:**
v8.6.15
**Node版本:**
v12.16.1
**出现概率:**
100%
**出现的问题 (BUG):**
```bash
12月 13 05:59:47 gamesever systemd[1]: Started MCSManager.
12月 13 05:59:47 gamesever node[22911]: internal/modules/cjs/loader.js:985
12月 13 05:59:47 gamesever node[22911]:   throw err;
12月 13 05:59:47 gamesever node[22911]:   ^
12月 13 05:59:47 gamesever node[22911]: Error: Cannot find module 'fs-extra'
12月 13 05:59:47 gamesever node[22911]: Require stack:
12月 13 05:59:47 gamesever node[22911]: - /opt/MCSManager/app.js
12月 13 05:59:47 gamesever node[22911]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
12月 13 05:59:47 gamesever node[22911]:     at Function.Module._load (internal/modules/cjs/loader.js:864:27)
12月 13 05:59:47 gamesever node[22911]:     at Module.require (internal/modules/cjs/loader.js:1044:19)
12月 13 05:59:47 gamesever node[22911]:     at require (internal/modules/cjs/helpers.js:77:18)
12月 13 05:59:47 gamesever node[22911]:     at Object.<anonymous> (/opt/MCSManager/app.js:34:14)
12月 13 05:59:47 gamesever node[22911]:     at Module._compile (internal/modules/cjs/loader.js:1158:30)
12月 13 05:59:47 gamesever node[22911]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
12月 13 05:59:47 gamesever node[22911]:     at Module.load (internal/modules/cjs/loader.js:1002:32)
12月 13 05:59:47 gamesever node[22911]:     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
12月 13 05:59:47 gamesever node[22911]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
12月 13 05:59:47 gamesever node[22911]:   code: 'MODULE_NOT_FOUND',
12月 13 05:59:47 gamesever node[22911]:   requireStack: [ '/opt/MCSManager/app.js' ]
12月 13 05:59:47 gamesever node[22911]: }
12月 13 05:59:47 gamesever systemd[1]: mcsm.service: Main process exited, code=exited, status=1/FAILURE
12月 13 05:59:47 gamesever systemd[1]: mcsm.service: Failed with result 'exit-code'.
12月 13 05:59:47 gamesever systemd[1]: mcsm.service: Scheduled restart job, restart counter is at 5.
12月 13 05:59:47 gamesever systemd[1]: Stopped MCSManager.
12月 13 05:59:47 gamesever systemd[1]: mcsm.service: Start request repeated too quickly.
12月 13 05:59:47 gamesever systemd[1]: mcsm.service: Failed with result 'exit-code'.
12月 13 05:59:47 gamesever systemd[1]: Failed to start MCSManager.
```
**复现操作步骤:**
``` sudo systemctl start mcsm ```
``` sudo journalctl -u mcsm -f ```

**Comment by Suwings** [comment]
原因可能是缺少安装依赖库。

你可以 cd 到 opt/mcsmanager 目录，执行 `npm install` 命令安装依赖库。

对于为何出现此问题，是不是安装的时候，你强制停止了？或者安装依赖库失败？

**Comment by yzy613** [comment]
> 原因可能是缺少安装依赖库。
> 
> 你可以 cd 到 opt/mcsmanager 目录，执行 `npm install` 命令安装依赖库。
> 
> 对于为何出现此问题，是不是安装的时候，你强制停止了？或者安装依赖库失败？

我最开始没有前置 sudo 运行 bash 脚本。按道理来讲，我重新运行 install.sh 脚本可以解决吧？（但是我重新运行了 3 次，依旧）

**Comment by yzy613** [comment]
```
ubuntu@localhost:/opt/MCSManager$ sudo npm install
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/sstur/nodeftpd.git /root/.npm/_cacache/tmp/git-clone-931d2776/.git
npm ERR! fatal: 不能为 '/root/.npm/_cacache/tmp/git-clone-931d2776/.git' 创建先导目录
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-13T14_38_54_143Z-debug.log
```

**Comment by Suwings** [comment]
依赖库安装失败，面板是无法正确启动的。

根据你提供的信息，我认为可能是权限导致的，可以尝试执行 `npm cache clean --force` 清理一下缓存文件，并且使用 su 命令转到 root 账号再尝试一下。或者将 .npm 文件/目录赋予正确权限。

**Comment by yzy613** [comment]
第一步
```bash
root@gamesever:/opt/MCSManager# npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
```
第二步
```bash
root@gamesever:/opt/MCSManager# npm install
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/prettier-34968a6b/doc.js'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/dockerode-518227e0/.travis.yml'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/iconv-lite-364952b1/encodings/sbcs-data.js'npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/iconv-lite-364952b1/encodings/tables'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/iconv-lite-364952b1/encodings/tables'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/iconv-lite-364952b1/encodings/tables'
npm ERR! code 128                            npm ERR! Command failed: git clone --mirror -q https://github.com/sstur/nodeftpd.git /root/.npm/_cacache/tmp/git-clone-ea450ff3/.git
npm ERR! fatal: 不能为 '/root/.npm/_cacache/tmp/git-clone-ea450ff3/.git' 创建先导目录
npm ERR! 
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/ipaddr.js-b2a0fa94/lib/ipaddr.js.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/iconv-lite-e43914f7/encodings/tables/eucjp.json'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/get-ready-4ddb31ae/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/get-ready-4ddb31ae/index.js'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/get-ready-4ddb31ae/History.md'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/iconv-lite-364952b1/encodings/tables'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/iconv-lite-364952b1/encodings/tables'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/iconv-lite-364952b1/encodings/tables'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/iconv-lite-364952b1/encodings/tables'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/iconv-lite-364952b1/encodings/tables'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/to-buffer-fb687ccb/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/to-buffer-fb687ccb/README.md'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/to-buffer-fb687ccb/test.js'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/iconv-lite-364952b1/encodings/utf16.js'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/iconv-lite-364952b1/encodings/utf7.js'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/body-parser-b25d131b/lib/types/raw.js'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/body-parser-b25d131b/lib/types/text.js'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/body-parser-b25d131b/lib/types/urlencoded.js'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/lib/internal'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/lib/internal'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/lib/internal'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/lib/internal'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/errors-browser.js'npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/errors.js'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/experimentalWarning.js'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/lib/internal'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/lib/internal'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/lib/internal'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/readable-browser.js'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/readable.js'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/lib/internal'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/lib/internal'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/lib/internal'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/package.json'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/CONTRIBUTING.md'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/GOVERNANCE.md'
npm WARN tar ENOENT: no such file or directory, open '/opt/MCSManager/node_modules/.staging/readable-stream-a5b5e10d/README.md'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-14T04_16_31_223Z-debug.log
```

**Comment by yzy613** [comment]
需要清理了之后再运行一次 install.sh 吗？

**Comment by yzy613** [comment]
好了。要把 clone 的 MCSManager 文件夹删掉，再来 install.sh 才弄好的
