### ISSUE TITLE
服务端进程启动失败

### ISSUE THREAD

**Issue by Steady66666** [Suwings/MCSManager#345]
**系统环境:**
CentOs8

**面板版本:**
8.6.16 发行版本

**Node版本:**
12.16.1

**出现概率:**
always

**出现的问题 (BUG):**
2020-12-14T23:05:04.709 INFO 控制面板正在启动中... 
2020-12-14T23:05:04.841 INFO OnlineFs - 正在初始化文件管理路由与中间件 
2020-12-14T23:05:04.849 INFO Module - 正在初始化用户管理模块
2020-12-14T23:05:04.854 INFO ======================================================== 
2020-12-14T23:05:04.855 INFO 管理用户已初始化 | 创建账号: #master 密码 123456 
2020-12-14T23:05:04.855 INFO ======================================================== 
2020-12-14T23:05:04.855 INFO 请注意！凡是以 # 符号开头的用户名,均视为管理员账号 
2020-12-14T23:05:04.855 INFO Module - 正在初始化服务端管理模块
2020-12-14T23:05:04.856 INFO Module - 正在初始化计划任务模块
2020-12-14T23:05:04.875 INFO HTTP - HTTP 模块监听: [ http://127.0.0.1:23333 ]
2020-12-14T23:05:04.876 INFO 配置文件: property.js 文件
2020-12-14T23:05:04.876 INFO 文档参阅: https://github.com/suwings/mcsmanager
2020-12-14T23:05:04.876 INFO 控制面板已经启动
2020-12-14T23:08:15.090 INFO 用户 #master 正在尝试登录... 
2020-12-14T23:08:15.092 INFO [ Login ] 用户: #master 密匙正确 准许登录 
2020-12-14T23:08:15.449 INFO [ Token ] 用户  #master  请求更新令牌 | 准许 
2020-12-14T23:08:15.514 INFO [ WS CREATE ] 新的 Ws 创建 会话ID: [ 3hWrAmZZ6tNi5d2Z3tIAWOzpsLh9sgSG ] 
2020-12-14T23:08:15.515 INFO [ WebSocket INIT ]  用户: #master 与服务器建立链接 
2020-12-14T23:08:35.915 INFO [ 文件上传 ] 用户 #master 上传文件到 ./server/server_core/new_server_5306000 
2020-12-14T23:08:42.833 INFO 用户  #master  正在启动  new_server_5306000  服务端实例... 
2020-12-14T23:08:42.835 INFO Minecraft Server start - new_server_5306000
2020-12-14T23:08:42.835 INFO 服务器 [ new_server_5306000 ] 启动进程: 
2020-12-14T23:08:42.835 INFO ------------------------------- 
2020-12-14T23:08:42.836 INFO 启动:  java -Djline.terminal=jline.UnsupportedTerminal -jar paperclip.jar nogui 
2020-12-14T23:08:42.836 INFO 根: ./server/server_core/new_server_5306000 
2020-12-14T23:08:42.836 INFO ------------------------------- 
2020-12-14T23:08:42.847 ERROR 服务端进程启动失败，建议检查启动命令与参数是否正确，pid:
2020-12-14T23:08:42.850 ERROR 服务器运行时异常,建议检查配置与环境
2020-12-14T23:08:42.851 ERROR Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs: [
    '-Djline.terminal=jline.UnsupportedTerminal',
    '-jar',
    'paperclip.jar',
    'nogui'
  ]
}
2020-12-14T23:08:42.856 ERROR 错误报告:
2020-12-14T23:08:42.856 ERROR TypeError: Cannot read property 'pid' of undefined
    at ChildProcess.<anonymous> (/opt/MCSManager/core/Process/BaseMcserver.js:298:107)
    at ChildProcess.emit (events.js:311:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-12-14T23:08:58.460 INFO [Online Fs] 管理员 #master 访问服务端存放目录 
2020-12-14T23:09:22.638 INFO [ WebSocket CLOSE ] 用户 #master 已经断开链接 

**复现操作步骤:**
wget -qO- https://gitee.com/Suwingser/MCSManager-installer/raw/master/install.sh | bash
并且启动额

**Comment by Steady66666** [comment]
额，环境没弄好。。。
Java：
`

yum install java-1.8.0-openjdk
--


`
`java -version
`
Node：
先确认系统是否安装过epel-release包
`yum info epel-release`
提示没有安装则执行安装命令：
`yum install epel-release`
`sudo yum install nodejs`
检查版本:
`node -v`
