### ISSUE TITLE
启动异常

### ISSUE THREAD

**Issue by LinHeLurking** [Suwings/MCSManager#35]
错误报告如下：

[ ERROR ]
--------Error-------

[ ERROR ]  UncaughtException 机制错误报告:
{ Error: listen EADDRINUSE :::23333
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at Server.listen (net.js:1465:7)
    at Function.serverListen [as listen] (/home/mc/MCSManager/node_modules/express-ws/lib/index.js:42:40)
    at initializationProm (/home/mc/MCSManager/app.js:248:9)
    at Object.<anonymous> (/home/mc/MCSManager/app.js:265:3)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 23333 }
--------Error-------

**Comment by LinHeLurking** [comment]
从报告来看是端口应该被占用的问题？不过也没有别的程序占用这个端口呀?

**Comment by Suwings** [comment]
你使用的版本是什么？建议你打开 ./prototype.js 文件，更改端口号码尝试一下(切记不要输入ip)。

稍后我将对当前版本进行一轮这样的测试。

**Comment by Suwings** [comment]
刚刚测试了一下，只发现在端口被占用时启动这种错误，你能确定没有别的程序占用吗？
其他情况我均没有发现这种错误。

**Comment by LinHeLurking** [comment]
我买的新的服务器拿来当MCserver的，所以几乎没有什么别的程序。 这个问题貌似是会在此程序退出之后再次启动的时候出现，可能是上一次的程序没有正常退出？但是我查进程又查不到。

**Comment by Suwings** [comment]
这种现象现在还出现吗？退出使用 `Ctrl+c` 退出。
> 这个问题貌似是会在此程序退出之后再次启动的时候出现
这种情况我在 Windows 与另外一台 Linux 下反复重启与直接关闭等测试，均未发现这个问题。

**Comment by LinHeLurking** [comment]
我的确是使用CTRL+C退出的。
不过后来我也没有复现这个问题，或许是云主机的问题，不是程序的问题。
