### ISSUE TITLE
无法使用基本参数中java路径。

### ISSUE THREAD

**Issue by NEIKI19914** [Suwings/MCSManager#360]
**系统环境:**window server 2019

**面板版本:**发行版本: 8.6.15 发行版本

**Node版本:**12.16.0.0

**出现概率:**100%

**出现的问题 (BUG):**设置了java路径完全没效，任何格式都测试了，以前同时装2个JAVAJDK的时候使用过。
                                    安装JAVA8JDK后，卸除JAVA11JDK显示如下。
 [01/11 05:59:16] [ERROR] 服务端进程启动失败，建议检查启动命令与参数是否正确，pid:
[01/11 05:59:16] [ERROR] 服务器运行时异常,建议检查配置与环境
[01/11 05:59:16] [ERROR] Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs: [
    '-server',
    '-Xms8G',
    '-Xmx8G',
    '-XX:+UseG1GC',
    '-XX:+UnlockExperimentalVMOptions',
    '-XX:MaxGCPauseMillis=100',
    '-XX:+DisableExplicitGC',
    '-XX:TargetSurvivorRatio=90',
    '-XX:G1NewSizePercent=50',
    '-XX:G1MaxNewSizePercent=80',
    '-XX:G1MixedGCLiveThresholdPercent=50',
    '-XX:+AlwaysPreTouch',
    '-XX:+UseLargePagesInMetaspace',
    '-jar',
    'forge-1.12.2-14.23.5.2854.jar'
  ]
}
[01/11 05:59:16] [ERROR] 错误报告:
[01/11 05:59:16] [ERROR] TypeError: Cannot read property 'pid' of undefined
    at ChildProcess.<anonymous> (D:\MCSManager_Win\core\Process\BaseMcserver.js:298:107)
    at ChildProcess.emit (events.js:321:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
其中  path: 'java',这里还是默认值，而面板设置我已经改成C:\Program Files\Java\jdk1.8.0_271\jre\bin\javaw.exe了。
**复现操作步骤:**没有重现，直接是无效的，在装有java8和java11的同时，只会启动java11，因为海绵服只能使用java8，无法指定路径导致1.16.4paper与插件作者推荐使用java11会有性能下降。

**Comment by NEIKI19914** [comment]
补充一下，其装java8jer虚拟机又可以正常启动，未改参数该启动路径应该是C:\Program Files\Java\jdk1.8.0_271\jre\bin\javaw.exe,可我已经完全将jdk1.8.0卸除了，理应是启动无效。

**Comment by NEIKI19914** [comment]
Warning! You're running an outdated version of Java
============================================================
* QuickShop will stop being compatible with this Java build
* since we released 1.17 updates.
*
* You should schedule an upgrade for Java on your server,
* because we will drop support with any version Java that
* lower Java 11.
*
* That means:
* 1) The new version of QuickShop for 1.17 updates will stop working on your server.
* 2) No more supporting for QuickShop that running
* on an outdated Java builds.
* 3) You will get performance improvements in the
* new version of Java builds.
* 
* Why:
* 1) We didn't want to keep compatibility with legacy software
* and systems. As Paper did it, we will follow the step.
* 2) Newer Java builds support legacy plugin that built for 8 
* or legacy, so the most plugins will still working.
* 3) New Java API allows access resources and processing it
*  faster than before, and that means performance improvement.
* 
* What should I do?
* You should update your server Java builds as soon as you can.
* Java 11 or any version after 11 is okay. 
*
* Most plugins can run on Java 11+ without problems un-
* less the code is really bad/hacky and you should uninstall it.
*
* You can get Java at here:
* https://www.oracle.com/java/technologies/javase-downloads.html
* And we recommended Java SE 11 (LTS) build for Minecraft Server.
*
*
* Current Java version: 1.8.0_271
插件作者
[io.papermc.paper.util.PaperJvmChecker] ************************************************************
[06:20:28 WARN]: [io.papermc.paper.util.PaperJvmChecker] * WARNING - YOU ARE RUNNING AN OUTDATED VERSION OF JAVA.
[06:20:28 WARN]: [io.papermc.paper.util.PaperJvmChecker] * PAPER WILL STOP BEING COMPATIBLE WITH THIS VERSION OF
[06:20:28 WARN]: [io.papermc.paper.util.PaperJvmChecker] * JAVA WHEN MINECRAFT 1.17 IS RELEASED.
[06:20:28 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[06:20:28 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Please update the version of Java you use to run Paper
[06:20:28 WARN]: [io.papermc.paper.util.PaperJvmChecker] * to at least Java 11. When Paper for Minecraft 1.17 is
[06:20:28 WARN]: [io.papermc.paper.util.PaperJvmChecker] * released support for versions of Java before 11 will
[06:20:28 WARN]: [io.papermc.paper.util.PaperJvmChecker] * be dropped.
[06:20:28 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[06:20:28 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Current Java version: 1.8.0_271
[06:20:28 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[06:20:28 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Check this forum post for more information: 
[06:20:28 WARN]: [io.papermc.paper.util.PaperJvmChecker] *   https://papermc.io/java11
[06:20:28 WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************
服务器核心作者都推荐使用11，可我是群组服需要使用java8开模组服，希望面板能修复该问题，去年9月多开算使用该面板，很不错。

**Comment by Suwings** [comment]
在logs文件夹中有日志文件，你将日志文件中启动服务器时使用的命令复制来看看。

另外关于路径的话，你使用java.exe试试。bor
比如：C:\Program Files\Java\jdk1.8.0_271\jre\bin\java.exe

**Comment by NEIKI19914** [comment]
> 在日志文件夹中有日志文件，您将在日志文件中启动服务器时使用的命令复制来看看。
> 
> Bor关于
> ：C：\ Program Files \ Java \ jdk1.8.0_271 \ jre \ bin \ java.exe

2021-01-12T08:30:11.746 INFO 控制面板正在启动中... 
2021-01-12T08:30:13.229 INFO OnlineFs - 正在初始化文件管理路由与中间件 
2021-01-12T08:30:13.357 INFO Module - 正在初始化用户管理模块
2021-01-12T08:30:13.363 INFO Module - 正在初始化服务端管理模块
2021-01-12T08:30:13.420 INFO Module - 正在初始化计划任务模块
2021-01-12T08:30:13.497 INFO HTTP - HTTP 模块监听: [ http://[33m127.0.0.1[39m:23333 ]
2021-01-12T08:30:13.499 INFO 配置文件: property.js 文件
2021-01-12T08:30:13.499 INFO 文档参阅: https://github.com/suwings/mcsmanager
2021-01-12T08:30:13.499 INFO 控制面板已经启动
2021-01-12T08:31:00.896 INFO 用户 #master 正在尝试登录... 
2021-01-12T08:31:00.899 INFO [ Login ] 用户: #master 密匙正确 准许登录 
2021-01-12T08:31:01.261 INFO [ Token ] 用户  #master  请求更新令牌 | 准许 
2021-01-12T08:31:01.321 INFO [ WS CREATE ] 新的 Ws 创建 会话ID: [ KvlD8ntP2sY6MW-vQ711PH2-S7ZQmWmj ] 
2021-01-12T08:31:01.324 INFO [ WebSocket INIT ]  用户: #master 与服务器建立链接 
2021-01-12T08:31:30.345 INFO [Pandmod] >>> 准许用户 #master 控制台监听 
2021-01-12T08:31:31.483 INFO 用户  #master  正在启动  Pandmod  服务端实例... 
2021-01-12T08:31:31.486 INFO Minecraft Server start - Pandmod
2021-01-12T08:31:31.487 INFO 服务器 [ Pandmod ] 启动进程: 
2021-01-12T08:31:31.488 INFO ------------------------------- 
2021-01-12T08:31:31.488 INFO 自定义参数启动:  java -server -Xms8G -Xmx8G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AlwaysPreTouch -XX:+UseLargePagesInMetaspace -jar forge-1.12.2-14.23.5.2854.jar 
2021-01-12T08:31:31.491 INFO 根: ./server/server_core/Pandmod/ 
2021-01-12T08:31:31.492 INFO ------------------------------- 
2021-01-12T08:31:31.564 INFO [Pandmod] >>> 进程创建 
2021-01-12T08:31:38.861 INFO [Pandmod] >>> 进程退出 
一但安装JAVA11JDK后
[控制面板]: 暂无任何历史记录.
[控制面板]: 无法读取更多的服务端日志: 已到最顶端.. [_b_r_][MCSMANAGER] -------------------------------------------------------------- 
[MCSMANAGER] [ 2021/0/2 8:34:19 ]: 服务端 Pandmod 执行开启命令. 
[MCSMANAGER] -------------------------------------------------------------- 
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
[MCSMANAGER] -------------------------------------------------------------- 
[MCSMANAGER] [ 2021/0/2 8:34:26 ]: 服务端 Pandmod 关闭. 
参数设置中java路径是C:\Program Files\Java\jre1.8.0_271\bin\java.exe，之前也只能使用这个，java8jdk的虚拟机也无法用路径使用。

**Comment by adsa562** [comment]
個人建議，你SpongeForge服或BC，二選一移到虛擬機內執行吧...

**Comment by NEIKI19914** [comment]
> 个人建议，你SpongeForge服或BC，二选一移到虚拟机内部执行吧...

我现在用的是window server 2019操作系统,如果改为虚拟机内部执行会让现在的服务器性能下降,多租一台会让预算过多.
