### ISSUE TITLE
最新版本服务端进程启动失败

### ISSUE THREAD

**Issue by Redbeanw44602** [Suwings/MCSManager#366]
**系统环境:**
Debian10 使用提供的一键脚本安装，过程无报错

**面板版本:**
8.6.17

**Node 版本:**
12.16.1

**出现概率:**
100%

**出现的问题 (BUG):**
服务端进程启动失败，建议检查启动参数是否正确
报错日志：
```
2021-01-30T12:28:28.436 ERROR 错误报告:
2021-01-30T12:28:28.436 ERROR TypeError: Cannot read property 'pid' of undefined
    at ChildProcess.<anonymous> (/opt/MCSManager/core/Process/BaseMcserver.js:298:107)
    at ChildProcess.emit (events.js:311:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-01-30T12:28:31.326 INFO 用户  #xxx 正在启动  Lobby  服务端实例... 
2021-01-30T12:28:31.326 INFO Minecraft Server start - Lobby
2021-01-30T12:28:31.326 INFO 服务器 [ Lobby ] 启动进程: 
2021-01-30T12:28:31.326 INFO ------------------------------- 
2021-01-30T12:28:31.326 INFO 自定义参数启动:  java -jar nukkit-1.0-SNAPSHOT.jar 
2021-01-30T12:28:31.326 INFO 根: /data/minecraft/lobby 
2021-01-30T12:28:31.326 INFO ------------------------------- 
2021-01-30T12:28:31.331 ERROR 服务端进程启动失败，建议检查启动命令与参数是否正确，pid:
2021-01-30T12:28:31.332 ERROR 服务器运行时异常,建议检查配置与环境
2021-01-30T12:28:31.332 ERROR Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs: [ '-jar', 'nukkit-1.0-SNAPSHOT.jar' ]
}
```

**复现操作步骤:**
创建新服务端，然后启动。
（无论是否使用自定义参数都会出现问题。SSH内操作一切正常）

**Comment by Redbeanw44602** [comment]
添加/usr/bin/java软链即可。。。
已解决
