### ISSUE TITLE
npm install 错误，不知道是什么问题

### ISSUE THREAD

**Issue by Ar-Hyk** [Suwings/MCSManager#387]
## **零、系统信息**

**系统环境:CentOS 7.6**

**面板版本:这个……是最新的吧**

**Node 版本:12.16.1**

**出现概率:在我这里就是一直出现**

**出现的问题 (BUG):依赖安装失败？**

## **一、使用一行命令快速安装**

按照说明使用以下命令安装
```
wget -qO- https://gitee.com/Suwingser/MCSManager-installer/raw/master/install.sh | bash
```

安装过程出现以下提示
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/nodeftpd/nodeftpd.git
npm ERR! 
npm ERR! fatal: unable to access 'https://github.com/nodeftpd/nodeftpd.git/': Encountered end of file
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-10T05_58_59_582Z-debug.log
```

查询运行状态（Status: systemctl status mcsm）
```
● mcsm.service - MCSManager
Loaded: loaded (/usr/lib/systemd/system/mcsm.service; disabled; vendor preset: disabled)
Active: failed (Result: start-limit) since Wed 2021-03-10 14:00:17 CST; 1min 19s ago
Process: 25187 ExecStart=/usr/bin/node /opt/MCSManager/app.js (code=exited, status=1/FAILURE)
Main PID: 25187 (code=exited, status=1/FAILURE)

Mar 10 14:00:17 VM-12-14-centos node[25187]: }
Mar 10 14:00:17 VM-12-14-centos systemd[1]: mcsm.service: main process exited, code=exited, status=1/FAILURE
Mar 10 14:00:17 VM-12-14-centos systemd[1]: Unit mcsm.service entered failed state.
Mar 10 14:00:17 VM-12-14-centos systemd[1]: mcsm.service failed.
Mar 10 14:00:17 VM-12-14-centos systemd[1]: mcsm.service holdoff time over, scheduling restart.
Mar 10 14:00:17 VM-12-14-centos systemd[1]: Stopped MCSManager.
Mar 10 14:00:17 VM-12-14-centos systemd[1]: start request repeated too quickly for mcsm.service
Mar 10 14:00:17 VM-12-14-centos systemd[1]: Failed to start MCSManager.
Mar 10 14:00:17 VM-12-14-centos systemd[1]: Unit mcsm.service entered failed state.
Mar 10 14:00:17 VM-12-14-centos systemd[1]: mcsm.service failed.
```

## **二、尝试使用手动安装**

按照以下步骤尝试手动安装

```
# 切换到安装目录，没有此目录请执行 mkdir /opt/
cd /opt/
# 下载运行环境
wget https://npm.taobao.org/mirrors/node/v12.16.1/node-v12.16.1-linux-x64.tar.gz
# 解压文件
tar -zxvf node-v12.16.1-linux-x64.tar.gz
# 链接程序到环境变量中
ln -s /opt/node-v12.16.1-linux-x64/bin/node /usr/bin/node
ln -s /opt/node-v12.16.1-linux-x64/bin/npm /usr/bin/npm
# 克隆仓库(若没有 git，请安装它，如 apt install -y git)
git clone https://github.com/suwings/mcsmanager.git
# 进入目录
cd mcsmanager/
# 安装依赖库
npm install
# 启动面板
npm start 
# 关闭面板使用 Ctrl+C 快捷键即可
```

当进行到“安装依赖库（npm install）”一步时，产生以下提示信息（与上方相似）

```
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/nodeftpd/nodeftpd.git /root/.npm/_cacache/tmp/git-clone-a7234bc9/.git
npm ERR! warning: templates not found /tmp/pacote-git-template-tmp/git-clone-ca647362
npm ERR! fatal: unable to access 'https://github.com/nodeftpd/nodeftpd.git/': Encountered end of file
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-10T05_38_50_684Z-debug.log
[root@VM-12-14-centos MCSManager]# npm install ftpd
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/nodeftpd/nodeftpd.git
npm ERR! 
npm ERR! fatal: unable to access 'https://github.com/nodeftpd/nodeftpd.git/': Encountered end of file
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-10T05_44_17_519Z-debug.log
```

运行启动面板（npm start），以下提示信息（ftpd依赖错误？）

```
> mcsmanager@8.6.15 start /root/MCSManager
> node app.js

internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'ftpd'
Require stack:
- /root/MCSManager/ftpd/ftpserver.js
- /root/MCSManager/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/root/MCSManager/ftpd/ftpserver.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/MCSManager/ftpd/ftpserver.js', '/root/MCSManager/app.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mcsmanager@8.6.15 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mcsmanager@8.6.15 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-10T06_24_38_242Z-debug.log
```

## **三、补充**

小白一个，啥也不会只会折腾，如果不是BUG，那么很抱歉打扰了……

github使用较少，回复可能较慢，如果需要提供其他信息，请联系：pnhyk@qq.com

**Comment by Ar-Hyk** [comment]
有大大给个解决方案吗？

**Comment by Suwings** [comment]
回复较晚还请理解，原因是https://github.com/nodeftpd/nodeftpd.git这个依赖库无法成功安装，此依赖库安装效率一直存在部分问题，在部分网络线路不是很好的地区或者其他，将有可能下载失败。

此依赖库现以在最新版本删除，这个是用于 FTP 功能依赖库，早在很久的先前版本就已经有删除FTP功能的设想，如今也算是付诸实行。

关于你这个情况，请重新采用一键安装脚本来进行MCSM安装，估计此问题将会得以解决。如有其他情况，欢迎继续反馈。

**Comment by Ar-Hyk** [comment]
重新采用一键安装脚本来进行MCSM安装，问题得到解决。非常感谢~

**Comment by Ar-Hyk** [comment]
重新采用一键安装脚本来进行MCSM安装，此问题已经得到了解决，非常感谢帮助




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月13日(星期六) 下午2:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Suwings/MCSManager] npm install 错误，不知道是什么问题 (#387)





 
回复较晚还请理解，原因是 https://github.com/nodeftpd/nodeftpd.git 这个依赖库无法成功安装，此依赖库安装效率一直存在部分问题，在部分网络线路不是很好的地区或者其他，将有可能下载失败。
 
此依赖库现以在最新版本删除，这个是用于 FTP 功能依赖库，早在很久的先前版本就已经有删除FTP功能的设想，如今也算是付诸实行。
 
关于你这个情况，请重新采用一键安装脚本来进行MCSM安装，估计此问题将会得以解决。如有其他情况，欢迎继续反馈。
