### ISSUE TITLE
启动服务端后面板崩溃

### ISSUE THREAD

**Issue by echoker** [Suwings/MCSManager#407]
**系统环境:** Windows Server 2012 R2

**面板版本:** 8.6.18

**Node 版本:** v12.16.0

**出现概率:** 总是

**出现的问题 (BUG):** 一旦启动服务端，面板就崩溃；使用的是官网下载的Windows整合版，多次重复下载，都出现同样的情况；以管理员身份运行也是如此；运行的服务端为BDS(加载了LiteLoader Mod框架)，启动正常，面板启动后也可以看到启动信息成功输出，但过几秒面板就会崩溃

![image](https://user-images.githubusercontent.com/39339568/114258912-ab51b880-99fc-11eb-9be1-5d136438865e.png)

**崩溃信息:**
`[04/10 12:51:20] [INFOError [ERR_STREAM_DESTROYED]: Cannot call write after a st
ream was destroyed
    at doWrite (_stream_writable.js:437:19)
    at writeOrBuffer (_stream_writable.js:425:5)
    at WriteStream.Writable.write (_stream_writable.js:316:11)
    at C:\Users\Administrator\Desktop\mcsm\node_modules\log4js\lib\appenders\std
out.js:5:20
    at C:\Users\Administrator\Desktop\mcsm\node_modules\log4js\lib\log4js.js:42:
5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (C:\Users\Administrator\Desktop\mcsm\node_modules\
log4js\lib\log4js.js:41:21)
    at C:\Users\Administrator\Desktop\mcsm\node_modules\log4js\lib\clustering.js
:23:26
    at Array.forEach (<anonymous>)
    at sendToListeners (C:\Users\Administrator\Desktop\mcsm\node_modules\log4js\
lib\clustering.js:23:13)
`

**Comment by Suwings** [comment]
删除 logs 文件夹，以管理员身份，在有权限的目录下运行，最好是新建一个文件夹再尝试一下。

如果依然崩溃，请复制一份最新的 log 文件上来，我便于检查。最新的日志文件在 `logs\current.log` 复制报错的几段重要的即可。

**Comment by echoker** [comment]
> 删除 logs 文件夹，以管理员身份，在有权限的目录下运行，最好是新建一个文件夹再尝试一下。
> 
> 如果依然崩溃，请复制一份最新的 log 文件上来，我便于检查。最新的日志文件在 `logs\current.log` 复制报错的几段重要的即可。

似乎没有什么有意义的内容：
```
2021-04-27T14:38:57.149 INFO [ WebSocket INIT ]  用户: #master 与服务器建立链接 
2021-04-27T14:39:03.359 INFO [new_server_5285000] >>> 准许用户 #master 控制台监听 
2021-04-27T14:39:26.059 INFO 用户  #master  正在启动  new_server_5285000  服务端实例... 
2021-04-27T14:39:26.148 INFO Minecraft Server start - new_server_5285000
2021-04-27T14:39:26.167 INFO 服务器 [ new_server_5285000 ] 启动进程: 
2021-04-27T14:39:26.169 INFO ------------------------------- 
2021-04-27T14:39:26.170 INFO 自定义参数启动:  bedrock_server.exe 
2021-04-27T14:39:26.171 INFO 根: C:\Users\Administrator\Desktop\BDS 
2021-04-27T14:39:26.173 INFO ------------------------------- 
2021-04-27T14:39:26.263 INFO [new_server_5285000] >>> 进程创建 
2021-04-27T14:40:18.190 INFO [ WebSocket CLOSE ] 用户 #master 已经断开链接 
```

崩溃后的报错都不在`logs\current.log`里，已使用管理员身份运行面板

**Comment by echoker** [comment]
> 删除 logs 文件夹，以管理员身份，在有权限的目录下运行，最好是新建一个文件夹再尝试一下。
> 
> 如果依然崩溃，请复制一份最新的 log 文件上来，我便于检查。最新的日志文件在 `logs\current.log` 复制报错的几段重要的即可。

同样的服务端，在Windows 10运行正常，面板没有崩溃

**Comment by Suwings** [comment]
> > 删除 logs 文件夹，以管理员身份，在有权限的目录下运行，最好是新建一个文件夹再尝试一下。
> > 如果依然崩溃，请复制一份最新的 log 文件上来，我便于检查。最新的日志文件在 `logs\current.log` 复制报错的几段重要的即可。
> 
> 同样的服务端，在Windows 10运行正常，面板没有崩溃

那基本可以确定是系统环境的问题，可能是原先的Windows Server 2012 R2系统环境过于干净，面板整合包自带的环境不足以支持正常运行导致的。

建议你去nodejs官方网站下载nodejs的msi格式的安装包，完全的安装node运行环境，再删除面板自带的node_app.exe文件，使用新的cmd窗口输入node app.js 来运行。

估计此问题将得到解决。略微麻烦，如果实在不想做还是用win10吧。谢谢你的反馈。
