### ISSUE TITLE
服务器启动异常

### ISSUE THREAD

**Issue by masnn** [Suwings/MCSManager#61]
```
--------Error-------

[ ERROR ]  UncaughtException 机制错误报告:
TypeError: Cannot read property 'pid' of undefined
    at ChildProcess.process.on (D:\Workspace\htdocs\MCSManager\core\Process\BaseMcserver.js:129:113)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:236:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
--------Error-------
```
![image](https://user-images.githubusercontent.com/29992205/44956081-cc6ed600-aef0-11e8-99ba-a87938c7082c.png)
![image](https://user-images.githubusercontent.com/29992205/44956094-f7f1c080-aef0-11e8-89ca-364c1b291110.png)
![image](https://user-images.githubusercontent.com/29992205/44956096-09d36380-aef1-11e8-9e96-64b915f58728.png)

服务端文件已经放入并在外部环境可以正常启动

**Comment by masnn** [comment]
好的，谢谢，问题已解决。
