### ISSUE TITLE
Bedrock Delicate Server的支持？

### ISSUE THREAD

**Issue by Vibiry** [Suwings/MCSManager#86]
https://minecraft.net/en-us/download/server/bedrock/

**Comment by Suwings** [comment]
应该是支持的，将 bedrock_server.exe 上传到你的服务端根目录，然后在自定义参数中设置 `bedrock_server.exe` 为启动命令即可，软件便会启动此程序。

**Comment by Suwings** [comment]
Linux 下同理，服务端中有一个可执行文件为`bedrock_server`，你只需要在自定义参数中写上 `bedrock_server` 并且确保服务端根目录有这些文件，其他的全部兼容。

**Comment by tone0000** [comment]
linux 自定义命令无法启动服务器
[ ERROR ]  UncaughtException 机制错误报告:
TypeError: Cannot read property 'pid' of undefined
    at ChildProcess.process.on (/home/admin/MCSManager/core/Process/BaseMcserve
r.js:206:113)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
--------Error-------
使用的是官方文档的开服指令 LD_LIBRARY_PATH=. ./bedrock_server

**Comment by tone0000** [comment]
this.process.pid is null
undefined
--------Error-------

[ ERROR ]  
--------Error-------

[ ERROR ]  服务器启动时异常,建议检查配置与环境
{ Error: spawn LD_LIBRARY_PATH=. ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn LD_LIBRARY_PATH=.',
  path: 'LD_LIBRARY_PATH=.',
  spawnargs: [ './bedrock_server' ] }
--------Error-------

[ ERROR ]  
--------Error-------

[ ERROR ]  UncaughtException 机制错误报告:
TypeError: Cannot read property 'pid' of undefined
    at ChildProcess.process.on (/home/admin/MCSManager/core/Process/BaseMcserve
  errno: 'ENOENT',
  syscall: 'spawn LD_LIBRARY_PATH=.',
  path: 'LD_LIBRARY_PATH=.',
  spawnargs: [ './bedrock_server' ] }
--------Error-------

**Comment by Suwings** [comment]
经过测试，在Linux下，使用 `sudo LD_LIBRARY_PATH=. node app.js` 或 `sudo LD_LIBRARY_PATH=. npm start`  来启动 MCSM 面板，这样就可以让 MCSM 拥有此环境变量，这是 bedrock_server 启动必须的。

接下来只需要在 `服务端管理->参数->自定义命令` 中使用 `./bedrock_server` 命令来启动，不需要再加 `LD_LIBRARY_PATH=.` 即可。

类似于这样（我没有用root）:
![tim 20190220211200](https://user-images.githubusercontent.com/18360009/53094142-51f44a00-3554-11e9-9906-93cb1fbf584e.jpg)

不过这个方法是影响整个面板的。

**Comment by ivampiresp** [comment]
可以用脚本启动

**Comment by EternalAC** [comment]
修改了游戏模式和难度保存之后，重启服务器没有生效，怎么解决？

**Comment by htxzdfunny** [comment]
有一个重大的权限问题，用户可以自己替换目录下的所有文件，那么用户如果把bedrock_server.exe换成了后门程序……docker虽然可以解决问题但是对win系统很不友好

**Comment by Suwings** [comment]
这不是重大的权限问题，想要出租给陌生人，就应当使用 Docker ，否则不建议出租。

**Comment by leinchu** [comment]
这个软件是用来管理minecraft服务器端吗?是的话min嗯craft，客户端和服务器端又在哪里下载?谢谢！✌(̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)✌

**Comment by Suwings** [comment]
> 这个软件是用来管理minecraft服务器端吗?是的话min嗯craft，客户端和服务器端又在哪里下载?谢谢！✌(̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)✌

可以去 www.mcbbs.net 的资源板块寻找你要的服务端和客户端。
