### ISSUE TITLE
服务器异常关机后出现的异常

### ISSUE THREAD

**Issue by lupohan44** [Suwings/MCSManager#93]
-----------------------------------------------------------------------------
______  _______________________  ___
___   |/  /_  ____/_  ___/__   |/  /_____ _____________ _______ _____________
__  /|_/ /_  /    _____ \__  /|_/ /_  __ `/_  __ \  __ `/_  __ `/  _ \_  ___/
_  /  / / / /___  ____/ /_  /  / / / /_/ /_  / / / /_/ /_  /_/ //  __/  /
/_/  /_/  \____/  /____/ /_/  /_/  \__,_/ /_/ /_/\__,_/ _\__, / \___//_/
                                                        /____/
 + Version 8
 + Copyright 2013-2018 Suwings All rights reserved.
----------------------------------------------------------------------------
[ Online_Fs ]  初始化 Online_Fs 路由与中间件
[ ERROR ]
--------Error-------

[ ERROR ]  UncaughtException 机制错误报告:
SyntaxError: Unexpected token   in JSON at position 0
    at JSON.parse (<anonymous>)
    at DataModel.load (D:\MCSManager\core\DataModel.js:19:24)
    at Object.module.exports.load (D:\MCSManager\core\counter.js:29:15)
    at Object.module.exports.init (D:\MCSManager\core\counter.js:13:20)
    at initializationProm (D:\MCSManager\app.js:243:13)
    at Object.<anonymous> (D:\MCSManager\app.js:285:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
--------Error-------

**Comment by lupohan44** [comment]
https://github.com/Suwings/MCSManager/issues/29
这是上次的反馈

**Comment by lupohan44** [comment]
删除core\info.json就能解决 能否在程序里自行判断文件是否损坏呢

**Comment by Suwings** [comment]
感谢提供意见，的确如此，异常关机有一定几率导致这个文件破损，我们过段时间会修改这个问题。

谢谢。

**Comment by pppwaw** [comment]
我记得这个好像是概率性，我这里有的时候启动会出现这种状况，重启即可

**Comment by lupohan44** [comment]
> 我记得这个好像是概率性，我这里有的时候启动会出现这种状况，重启即可

重启无效 必须删除info.json文件

**Comment by lxdklp** [comment]
我强制断电后也出现了这种情况，谢谢你的方法。但是新版本没有core\info.json了，变为mcsmanager\daemon\data\Config\global.json（如果后面还有人出现这个问题请前往这个新目录）
